// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbyrenomabsdgxphhfdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxieXJlbm9tYWJzZGd4cGhoZmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4Njg4NjMsImV4cCI6MjA1NDQ0NDg2M30.mxQYUT90H_SLv7MS-SA8waFKnrk-EYTt0XAX7E9BU6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);